server:
  port: 9005

spring:
  application:
    name: hystrix-dasboard #服务注册到Eureka上使用的名称

#eureka:
#  client:
#    service-url:  # 集群情况下如下，如果是单机版，只需要配置单机版Eureka地址
#      defaultZone: http://localhost:7001/eureka/,http://localhost:7002/eureka/
#  instance:
#    instance-id: hystrix-dasboard-9005
#    prefer-ip-address: true #访问路径显示IP地址
#
#info:   # 在Eureka上点击服务时会跳转到个404页面，可配置这里让他跳转到服务简介的一个页面，信息如下配置
#  app.name: wuzz
#  company.name: www.wuzz.com
#  build.artifactId: hystrix-dasboard
#  build.version: 1.0
