server:
  port: 9008
spring:
  rabbitmq:
    host: 192.168.1.101
    username: guest
    password: guest
    port: 5672
  application:
    name: turbine-amqp #服务注册到Eureka上使用的名称
turbine:
  aggregator:
    cluster-config: default
  app-config: RIBBON-SERVER,ribbon-server-two #指定了需要收集监 控信息的服务名
  cluster-name-expression: new String("default") #参数指定了集群名称为default
  combine-host-port: true
# true 同一主机上的服务通过host和port的组合来进行区分，默认为true
# false 时 在本机测试时 监控中host集群数会为1了 因为本地host是一样的
eureka:
  client:
    service-url:  # 集群情况下如下，如果是单机版，只需要配置单机版Eureka地址
      defaultZone: http://localhost:7001/eureka/,http://localhost:7002/eureka/
  instance:
    instance-id: hystrix-dasboard-turbine-amqp
    prefer-ip-address: true #访问路径显示IP地址
#
#info:   # 在Eureka上点击服务时会跳转到个404页面，可配置这里让他跳转到服务简介的一个页面，信息如下配置
#  app.name: wuzz
#  company.name: www.wuzz.com
#  build.artifactId: hystrix-dasboard
#  build.version: 1.0

