server:
  port: 8881

spring:
  activemq:
    broker-url: tcp://192.168.1.101:61616
    user: admin
    password: admin
    pool:
      enabled: true
    packages:
      trust-all: true   #  如果使用ObjectMessage传输对象，必须要加上这个信任包，否则会报ClassNotFound异常
  jms:
    pub-sub-domain: true  # 启动主题消息
