server:
  port: 9002

spring:
  rabbitmq:
    host: 192.168.1.101
    username: guest
    password: guest
    port: 5672
  application:
    name: ribbon-server-two #服务注册到Eureka上使用的名称

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:7001/eureka/,http://localhost:7002/eureka/
  instance:
    instance-id: ribbon-server-9002
    prefer-ip-address: true #访问路径显示IP地址
